Repository cuentoneta/cuentoneta, pull requests merged in 2023-05, with the labels that each got.

#209 [TL-#93] Agregar angular universal
  .eslintrc.json
  .storybook/main.js
  api/index.js
  api/story/read.ts
  e2e/.eslintrc.json
  e2e/cypress.config.ts
  e2e/project.json
  jest.preset.js
  migrations.json
  nx.json
  package.json
  pnpm-lock.yaml
  project.json
  src/app/app.module.ts
  src/app/app.server.module.ts
  src/app/providers/story.service.ts
  src/main.server.ts
  src/main.ts
  src/ssr.server.ts
  storybook-migration-summary.md
  tailwind.config.js
  tsconfig.server.json
  vercel.json
Labels: 🏎️ mejora

#217 [#206 - FE] Adaptar altura y estilos de cards en vista storylist
  src/app/components/story-card-skeleton/story-card-skeleton.component.html
  src/app/components/story-card-skeleton/story-card-skeleton.component.scss
  src/app/components/story-card/story-card.component.html
  src/app/components/story-card/story-card.component.scss
  src/app/components/story-edition-date-label/story-edition-date-label.component.scss
  src/assets/scss/theme.scss
Labels: 🦟 bug, 🏎️ mejora

#222 [#200 - FE]: Agregados links de social media a componente footer
  src/app/components/footer/footer.component.html
Labels: 🏎️ mejora

#225 [#223] - Uso de ngOptimizedImage para imágenes de footer
  src/app/components/footer/footer.component.html
  src/app/components/header/header.component.html
  src/app/pages/home/home.component.html
Labels: 🏎️ mejora

#229 [#118 | DOCS] - Documentación para abrir proyecto
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  MVV.md
  README.md
  ROADMAP.md
Labels: 📝 documentación

#258 [#113] - Agregado soporte para configuración de layouts de skeletons
  scripts/set-environment.ts
  src/app/components/story-list-card-deck/story-list-card-deck.component.ts
  src/app/models/content.model.ts
  src/app/pages/home/home.component.html
  src/app/pages/story-list/story-list.component.html
  src/app/pages/story-list/story-list.component.ts
Labels: 🏎️ mejora

#267 [#266] - Eliminar hardcode de párrafos renderizados en vista previa
  src/app/components/story-card/story-card.component.html
  src/app/components/story-card/story-card.component.ts
Labels: 🦟 bug

#268 [#256] Mejoras en lista de historias en navbar
  src/app/components/story-navigation-bar/story-navigation-bar.component.html
  src/app/components/story-navigation-bar/story-navigation-bar.component.ts
Labels: 🏎️ mejora

#270 [#245] - Agrega navegación a storylist desde navbar
  src/app/components/story-navigation-bar/story-navigation-bar.component.html
  src/app/components/story-navigation-bar/story-navigation-bar.component.scss
Labels: 🏎️ mejora, 🤓 buen primer issue
