Repository cuentoneta/cuentoneta, pull requests merged in 2023-06, with the labels that each got.

#323 [#321] - Componentes restantes pasados a standalone y borrados modulos …
  src/app/app-routing.module.ts
  src/app/components/footer/footer.component.ts
  src/app/components/header/header.component.ts
  src/app/pages/home/home.component.ts
  src/app/pages/home/home.module.ts
  src/app/pages/story/story.component.ts
  src/app/pages/story/story.module.ts
  src/app/pages/storylist/storylist.component.ts
  src/app/pages/storylist/storylist.module.ts
Labels: 🏎️ mejora, 🏛️ arquitectura

#324 [#233] - Performance de las fuentes mejorado
  src/index.html
Labels: 🏎️ mejora

#328 [#326] Actualizar Nx a versión 16.3.2
  migrations.json
  package.json
  pnpm-lock.yaml
Labels: 🛠️ tooling

#330 [#239] - Correcciones en template de GitHub
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📝 documentación

#331 [#349] - Actualizar a Angular 16.1
  migrations.json
  package.json
  pnpm-lock.yaml
Labels: 🛠️ tooling

#332 [#211] - Establecer Vite como default para dev server
  project.json
  src/styles.scss
Labels: 🛠️ tooling

#342 [#257] - Generar componente dmca
  src/app/app-routing.module.ts
  src/app/pages/dmca/dmca.component.html
  src/app/pages/dmca/dmca.component.scss
  src/app/pages/dmca/dmca.component.spec.ts
  src/app/pages/dmca/dmca.component.ts
Labels: 🏎️ mejora, 📜 contenido

#347 [#276] Agrega navegación a link original de Story
  cms/schemas/story.ts
  src/app/components/bio-summary-card/bio-summary-card.component.html
  src/app/components/bio-summary-card/bio-summary-card.component.scss
  src/app/components/bio-summary-card/bio-summary-card.component.ts
  src/app/models/story.model.ts
  src/app/pages/story/story.component.html
  tsconfig.json
Labels: 🏎️ mejora

#348 [#346] - Realiza refinamiento en dmca component
  src/app/components/footer/footer.component.html
  src/app/pages/dmca/dmca.component.html
  src/app/pages/dmca/dmca.component.ts
Labels: 🏎️ mejora, 📜 contenido

#353 [#352] - Generación de link para compartir en Whatsapp en vista Story
  src/app/components/share-content/share-content.component.ts
Labels: 🦟 bug

#354 [#341] Agrega navegación a Storylist al clickear en título de preview
  src/app/components/storylist-card-deck/storylist-card-deck.component.html
  src/app/components/storylist-card-deck/storylist-card-deck.component.scss
  src/app/components/storylist-card-deck/storylist-card-deck.component.ts
  src/app/pages/home/home.component.html
Labels: 🏎️ mejora

#355 [#288] Mejoras en barra de navegación de storylist
  src/app/components/story-navigation-bar/story-navigation-bar.component.html
  src/app/components/story-navigation-bar/story-navigation-bar.component.scss
  src/app/components/story-navigation-bar/story-navigation-bar.component.ts
  src/app/pages/story/story.component.html
  src/app/pages/story/story.component.ts
Labels: 🏎️ mejora

#350 [#307] - 11 test de 19 corregidos
  package.json
  pnpm-lock.yaml
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/components/bio-summary-card/bio-summary-card.component.spec.ts
  src/app/components/footer/footer.component.spec.ts
  src/app/components/share-content/share-content.component.spec.ts
  src/app/components/story-card-skeleton/story-card-skeleton.component.spec.ts
  src/app/components/story-card/story-card.component.spec.ts
  src/app/components/story-edition-date-label/story-edition-date-label.component.spec.ts
  src/app/components/story-navigation-bar/story-navigation-bar.component.spec.ts
  src/app/components/storylist-card-deck/storylist-card-deck.component.spec.ts
  src/app/pages/about/about.component.spec.ts
Labels: 🛠️ tooling

#366 [#365] - Versión actualizada en el package.json
  package.json
Labels: 📝 documentación
