Repository cuentoneta/cuentoneta, pull requests merged in 2023-07, with the labels that each got.

#377 [#367] - Corrección de unit tests en header.componet.spec.ts
  src/app/components/header/header.component.spec.ts
Labels: 🔍 qa

#379 [#338] - Migrar Nx y scripts
  migrations.json
  nx.json
  package.json
  pnpm-lock.yaml
Labels: 🛠️ tooling

#381 [#360] Migrar AppCoponent a standalone
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.config.server.ts
  src/app/app.config.ts
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/app.server.module.ts
  src/app/components/header/header.component.ts
  src/app/components/story-navigation-bar/story-navigation-bar.component.ts
  src/app/components/storylist-card-deck/storylist-card-deck.component.ts
  src/app/pages/home/home.component.ts
  src/app/pages/story/story.component.ts
  src/main.server.ts
  src/main.ts
  src/ssr.server.ts
Labels: 🏛️ arquitectura

#382 [#378] - Corregir test de tooltip directive
  src/app/directives/tooltip.directive.spec.ts
Labels: 🔍 qa

#383 [#349] Agregar cuenta para Sanity Studio en entorno local
  CONTRIBUTING.md
  cms/package.json
  cms/pnpm-lock.yaml
  cms/sanity.config.ts
  package.json
Labels: 🛠️ tooling

#386 [#368] Agregar ambiente staging en Vercel
  .eslintrc.json
  scripts/set-environment.ts
Labels: 🛠️ tooling

#388 [#359] - Agregar propiedad url a schema story
  cms/schemas/story.ts
  src/api/story.service.ts
  src/api/storylist.service.ts
Labels: 🏎️ mejora

#389 [#359] - Agregar soporte para cuentos en formato video
  src/app/models/story.model.ts
  src/app/pages/story/story.component.html
  src/app/pages/story/story.component.scss
  src/app/pages/story/story.component.ts
Labels: 🏎️ mejora
